language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "14"
  - "16"
script:
  - npm run build && npm run test:prod
after_success:
  - npm run travis-deploy-once "npm run report-coverage"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
